import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#001e40",
        "primary-container": "#003366",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#a7c8ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#799dd6",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#1f477b",
        "secondary": "#745b00",
        "secondary-container": "#fecb00",
        "secondary-fixed": "#ffe08b",
        "secondary-fixed-dim": "#f1c100",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6e5700",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#584400",
        "tertiary": "#1b1f22",
        "tertiary-container": "#313437",
        "tertiary-fixed": "#e0e2e6",
        "tertiary-fixed-dim": "#c4c7ca",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#999ca0",
        "on-tertiary-fixed": "#191c1f",
        "on-tertiary-fixed-variant": "#44474a",
        "background": "#f9f9ff",
        "on-background": "#141b2b",
        "surface": "#f9f9ff",
        "surface-dim": "#d3daef",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#dce2f7",
        "surface-tint": "#3a5f94",
        "on-surface": "#141b2b",
        "on-surface-variant": "#43474f",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "surface-container": "#e9edff",
        "surface-container-high": "#e1e8fd",
        "surface-container-highest": "#dce2f7",
        "inverse-surface": "#293040",
        "inverse-on-surface": "#edf0ff",
        "inverse-primary": "#a7c8ff",
        "outline": "#737780",
        "outline-variant": "#c3c6d1",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "section-gap": "5rem",
        "stack-lg": "2rem",
        "container-max": "1280px",
        "margin-x": "2rem",
        "gutter": "1.5rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem"
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "label-bold": ["var(--font-archivo)", "sans-serif"],
        "stat-value": ["var(--font-montserrat)", "sans-serif"],
        "display-lg": ["var(--font-montserrat)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-montserrat)", "sans-serif"],
        "headline-lg": ["var(--font-montserrat)", "sans-serif"],
        "headline-xl": ["var(--font-montserrat)", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-bold": ["14px", { "lineHeight": "1", "fontWeight": "700" }],
        "stat-value": ["24px", { "lineHeight": "1", "fontWeight": "800" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "900" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "fontWeight": "800" }]
      }
    },
  },
  plugins: [],
};
export default config;
